---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3.9-jdk-8

inputs:
  - name: repository-name

outputs:
  - name: target
    path: target

caches:
  - path: .m2/repository

run:
  path: sh
  args:
  - -exc
  - |
    mkdir -p .m2/repository
    mvn --settings repository-name/.maven.settings.xml install -DdockerComposeSkip -Ddockerfile.skip -Ddocker.skip -DskipITs -Dhttp.wait.skip -f repository-name/pom.xml -Dmaven.repo.local=.m2/repository
    cp -r repository-name/target/ .
