---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
- name: ras-deploy
- name: ras-collection-instrument-source

run:
  path: ras-deploy/scripts/deploy_collection_instrument.sh