---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
- name: ras-deploy

outputs:
- name: cf-database-env-vars

run:
  path: sh
  args:
  - -exc
  - |
    ras-deploy/scripts/get_database_uris.sh > cf-database-env-vars/setenv.sh
