---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
- name: ras-depoy

outputs:
- name: env-vars

run:
  path: ras-deploy/scripts/get_database_uris.sh