---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.6

inputs:
- name: repository-name

run:
  path: sh
  args:
    - -exc
    - |
      cd repository-name
      pip install -U pipenv
      make build
      make test
