---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sdcplatform/rasrm-acceptance-tests
    tag: "latest"

inputs:
- name: rasrm-acceptance-tests-source
- name: cf-database-env-vars
- name: ras-deploy

run:
  path: ras-deploy/scripts/rasrm-acceptance-tests/run_acceptance_tests.sh