---
resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

### START MICROSERVICE REPOS
resources:
- name: ras-party-source
  type: git
  source:
    uri: https://github.com/ONSdigital/ras-party.git
    branch: master

- name: ras-secure-message-source
  type: git
  source:
    uri: https://github.com/ONSdigital/ras-secure-message.git
    branch: master

- name: ras-backstage-source
  type: git
  source:
    uri: https://github.com/ONSdigital/ras-backstage.git
    branch: master

- name: ras-collection-instrument-source
  type: git
  source:
    uri: https://github.com/ONSdigital/ras-collection-instrument.git
    branch: master

- name: ras-frontstage-source
  type: git
  source:
    uri: https://github.com/ONSdigital/ras-frontstage.git
    branch: master
### END MICROSERVICE REPOS

- name: cf-cli-resource-ci
  type: cf-cli-resource
  source:
    api: {{cloudfoundry_api}}
    username: {{cloudfoundry_email}}
    password: {{cloudfoundry_password}}
    org: rmras
    space: concourse-ci
    skip_cert_check: true

- name: cf-resource-ci
  type: cf
  source:
    api: {{cloudfoundry_api}}
    username: {{cloudfoundry_email}}
    password: {{cloudfoundry_password}}
    organization: rmras
    space: concourse-ci
    skip_cert_check: true

jobs:
#- name: ras-party-unit-tests
#  plan:
#  - get: ras-party-source
#    trigger: true
#  - task: run-unit-tests
#    config:
#      platform: linux
#      image_resource:
#        type: docker-image
#        source:
#          repository: sdcplatform/python-pipenv-chrome
#      inputs:
#      - name: ras-party-source
#      params:
#        DATABASE_URI: sqlite://
#      run:
#        path: sh
#        dir: ras-party-source
#        args:
#        - -exc
#        - |
#          # Download quickfix for pipenv check error
#          pip install --upgrade --pre pipenv
#
#          echo $DATABASE_URI
#
#          pipenv install --dev
#          make test

- name: ras-party-ci-deploy
  plan:
  - get: ras-party-source
    trigger: true
  - put: create-database
    resource: cf-cli-resource-ci
    params:
      command: create-service
      service: rds
      plan: shared-psql
      service_instance: ras-party-db
      timeout: 300
      wait_for_service: true
  - put: push-app
    resource: cf-resource-ci
    params:
      current_app_name: ras-party-ci-migration
      manifest: ras-party-source/manifest.yml
      path: ras-party-source
      environment_variables:
        RAS_CASE_SERVICE_HOST: 'rm-case-service-ci-migration.apps.devtest.onsclofo.uk'
        RAS_CASE_SERVICE_PORT: '80'
        RAS_COLLEX_SERVICE_HOST: 'rm-collection-exercise-service-ci-migration.apps.devtest.onsclofo.uk'
        RAS_COLLEX_SERVICE_PORT: '80'
        RAS_IAC_SERVICE_HOST: 'iac-service-ci-migration.apps.devtest.onsclofo.uk'
        RAS_IAC_SERVICE_PORT: '80'
        RAS_NOTIFY_SERVICE_URL: 'http://rm-notify-gateway-ci-migration.apps.devtest.onsclofo.uk/emails/'
        RAS_OAUTH_SERVICE_HOST: 'django-oauth2-test-ci-migration.apps.devtest.onsclofo.uk'
        RAS_OAUTH_SERVICE_PORT: '80'
        RAS_PUBLIC_WEBSITE_HOST: 'ras-frontstage-ci-migration.apps.devtest.onsclofo.uk'
        RAS_PUBLIC_WEBSITE_PORT: '80'
        RAS_SURVEY_SERVICE_HOST: 'rm-survey-service-ci-migration.apps.devtest.onsclofo.uk'
        RAS_SURVEY_SERVICE_PORT: '80'
        RAS_NOTIFY_CONFIRM_PASSWORD_CHANGE_TEMPLATE: 'ba41c152-ad96-4255-9456-9e42de83f510'
        RAS_NOTIFY_EMAIL_VERIFICATION_TEMPLATE: '53c59576-8c3b-4298-99d1-b245ddd28500'
        RAS_NOTIFY_REQUEST_PASSWORD_CHANGE_TEMPLATE: 'c45c59ff-7771-4de4-a66b-ce50b108390a'
        SECURITY_USER_NAME: ((ci_security_user_name))
        SECURITY_USER_PASSWORD: ((ci_security_user_password))

- name: ras-secure-message-ci-deploy
  plan:
  - get: ras-secure-message-source
    trigger: true
  - put: create-database
    resource: cf-cli-resource-ci
    params:
      command: create-service
      service: rds
      plan: shared-psql
      service_instance: secure-message-db
      timeout: 300
      wait_for_service: true
  - put: cf-resource-ci
    params:
      current_app_name: ras-secure-message-ci-migration
      manifest: ras-secure-message-source/manifest.yml
      path: ras-secure-message-source
      environment_variables:
        JWT_ALGORITHM: 'HS256'
        JWT_SECRET: ((ci_jwt_secret))
        NOTIFICATION_API_KEY: ((test_notify_api_key))
        NOTIFICATION_TEMPLATE_ID: 'f6404844-a994-428c-a5d7-45a4e1cfff4b'
        NOTIFY_VIA_GOV_NOTIFY: '1'
        RM_NOTIFY_GATEWAY_URL: 'http://rm-notify-gateway-ci-migration.apps.devtest.onsclofo.uk/emails/'
        RAS_PARTY_SERVICE_HOST: 'ras-party-ci-migration.apps.devtest.onsclofo.uk'
        RAS_PARTY_SERVICE_PORT: '80'
        RM_CASE_SERVICE_HOST: 'rm-case-service-ci-migration.apps.devtest.onsclofo.uk'
        RM_CASE_SERVICE_PORT: '80'
        RAS_SM_PATH: '/home/vcap/app'
        SECURITY_USER_NAME: ((ci_security_user_name))
        SECURITY_USER_PASSWORD: ((ci_security_user_password))
        SERVICE_ID: 'ce3674b1-7b08-4377-a6a7-05b5722d4ea5'
        UAA_URL: 'http://uaa-ci-migration.apps.devtest.onsclofo.uk'
        CLIENT_ID: 'secure_message'
        CLIENT_SECRET: ((ci_secure_message_client_secret))
        USE_UAA: '1'

- name: ras-backstage-ci-deploy
  plan:
  - get: ras-backstage-source
    trigger: true
  - put: cf-resource-ci
    params:
      current_app_name: ras-backstage-ci-migration
      manifest: ras-backstage-source/manifest.yml
      path: ras-backstage-source
      environment_variables:
        RAS_SECURE_MESSAGING_JWT_SECRET: ((ci_jwt_secret))
        RAS_COLLECTION_INSTRUMENT_SERVICE_HOST: 'ras-collection-instrument-ci-migration.apps.devtest.onsclofo.uk'
        RAS_COLLECTION_INSTRUMENT_SERVICE_PORT: '80'
        RAS_OAUTH_SERVICE_HOST: 'django-oauth2-test-ci-migration.apps.devtest.onsclofo.uk'
        RAS_OAUTH_SERVICE_PORT: '80'
        RAS_PARTY_SERVICE_HOST: 'ras-party-ci-migration.apps.devtest.onsclofo.uk'
        RAS_PARTY_SERVICE_PORT: '80'
        RAS_SECURE_MESSAGING_SERVICE_HOST: 'ras-secure-message-ci-migration.apps.devtest.onsclofo.uk'
        RAS_SECURE_MESSAGING_SERVICE_PORT: '80'
        RM_CASE_SERVICE_HOST: 'rm-case-service-ci-migration.apps.devtest.onsclofo.uk'
        RM_CASE_SERVICE_PORT: '80'
        RM_COLLECTION_EXERCISE_SERVICE_HOST: 'rm-collection-exercise-service-ci-migration.apps.devtest.onsclofo.uk'
        RM_COLLECTION_EXERCISE_SERVICE_PORT: '80'
        RM_IAC_SERVICE_HOST: 'iac-service-ci-migration.apps.devtest.onsclofo.uk'
        RM_IAC_SERVICE_PORT: '80'
        RM_SAMPLE_SERVICE_HOST: 'rm-sample-service-ci-migration.apps.devtest.onsclofo.uk'
        RM_SAMPLE_SERVICE_PORT: '80'
        RM_SURVEY_SERVICE_HOST: 'rm-survey-service-ci-migration.apps.devtest.onsclofo.uk'
        RM_SURVEY_SERVICE_PORT: '80'
        SECURITY_USER_NAME: ((ci_security_user_name))
        SECURITY_USER_PASSWORD: ((ci_security_user_password))
        UAA_CLIENT_ID: 'ras_backstage'
        UAA_CLIENT_SECRET: ((ci_backstage_client_secret))
        UAA_SERVICE_URL: 'http://uaa-ci-migration.apps.devtest.onsclofo.uk'
        USE_UAA: '1'

- name: ras-collection-instrument-ci-deploy
  plan:
  - get: ras-collection-instrument-source
    trigger: true
  - put: create-database
    resource: cf-cli-resource-ci
    params:
      command: create-service
      service: rds
      plan: shared-psql
      service_instance: ras-ci-db
      timeout: 300
      wait_for_service: true
  - put: cf-resource-ci
    params:
      current_app_name: ras-collection-instrument-ci-migration
      manifest: ras-collection-instrument-source/manifest.yml
      path: ras-collection-instrument-source
      environment_variables:
        CASE_SERVICE_HOST: 'rm-case-service-ci-migration.apps.devtest.onsclofo.uk'
        CASE_SERVICE_PORT: '80'
        COLLECTION_EXERCISE_HOST: 'rm-collection-exercise-service-ci-migration.apps.devtest.onsclofo.uk'
        COLLECTION_EXERCISE_PORT: '80'
        PARTY_SERVICE_HOST: 'ras-party-ci-migration.apps.devtest.onsclofo.uk'
        PARTY_SERVICE_PORT: '80'
        JSON_SECRET_KEYS: ((ci_json_secret_keys))
        ONS_CRYPTOKEY: ((ci_collection_instrument_encryption_key))
        RABBITMQ_AMQP_COLLECTION_INSTRUMENT: ((ci_rabbitmq_amqp_collection_instrument)) # DANGEROUS!
        RABBITMQ_AMQP_SURVEY_RESPONSE: ((ci_rabbitmq_amqp_survey_response))
        RM_SURVEY_SERVICE_HOST: 'rm-survey-service-ci-migration.apps.devtest.onsclofo.uk'
        RM_SURVEY_SERVICE_PORT: '80'
        SECURITY_USER_NAME: ((ci_security_user_name))
        SECURITY_USER_PASSWORD: ((ci_security_user_password))

- name: ras-frontstage-ci-deploy
  plan:
  - get: ras-frontstage-source
    trigger: true
  - put: create-redis
    resource: cf-cli-resource-ci
    params:
      command: create-service
      service: elasticache-broker
      plan: small
      service_instance: rm-redis
      timeout: 300
      wait_for_service: true
  - put: cf-resource-ci
    params:
      current_app_name: ras-frontstage-ci-migration
      manifest: ras-frontstage-source/manifest.yml
      path: ras-frontstage-source
      environment_variables:
        JWT_SECRET: ((ci_jwt_secret))
        RAS_FRONTSTAGE_API_HOST: 'ras-frontstage-api-ci-migration.apps.devtest.onsclofo.uk'
        RAS_FRONTSTAGE_API_PORT: '80'
        RAS_SECURE_MESSAGE_SERVICE_HOST: 'ras-secure-message-ci-migration.apps.devtest.onsclofo.uk'
        RAS_SECURE_MESSAGE_SERVICE_PORT: '80'
        SECRET_KEY: ((ci_enrolement_code_encryption_key))
        SECURITY_USER_NAME: ((ci_security_user_name))
        SECURITY_USER_PASSWORD: ((ci_security_user_password))
