templates:
templates:
  ci:
    security_user: &ci_security_user
      actionSvc_connectionConfig_password: ((ci_security_user_password))
      actionSvc_connectionConfig_username: ((ci_security_user_name))
      caseSvc_connectionConfig_username: ((ci_security_user_name))
      caseSvc_connectionConfig_password: ((ci_security_user_password))
      collectionExerciseSvc_connectionConfig_username: ((ci_security_user_name))
      collectionExerciseSvc_connectionConfig_password: ((ci_security_user_password))
      collectionInstrumentSvc_connectionConfig_username: ((ci_security_user_name))
      collectionInstrumentSvc_connectionConfig_password: ((ci_security_user_password))
      internetAccessCodeSvc_connectionConfig_password: ((ci_security_user_password))
      internetAccessCodeSvc_connectionConfig_username: ((ci_security_user_name))
      partySvc_connectionConfig_username: ((ci_security_user_name))
      partySvc_connectionConfig_password: ((ci_security_user_password))
      sampleSvc_connectionConfig_username: ((ci_security_user_name))
      sampleSvc_connectionConfig_password: ((ci_security_user_password))
      security_user_name: ((ci_security_user_name))
      security_user_password: ((ci_security_user_password))
      surveySvc_connectionConfig_username: ((ci_security_user_name))
      surveySvc_connectionConfig_password: ((ci_security_user_password))
      CASE_USERNAME: ((ci_security_user_name))
      CASE_PASSWORD: ((ci_security_user_password))
      COLLECTION_EXERCISE_USERNAME: ((ci_security_user_name))
      COLLECTION_EXERCISE_PASSWORD: ((ci_security_user_password))
      COLLECTION_INSTRUMENT_USERNAME: ((ci_security_user_name))
      COLLECTION_INSTRUMENT_PASSWORD: ((ci_security_user_password))
      IAC_USERNAME: ((ci_security_user_name))
      IAC_PASSWORD: ((ci_security_user_password))
      PARTY_USERNAME: ((ci_security_user_name))
      PARTY_PASSWORD: ((ci_security_user_password))
      #TODO: Add 2 lines
      RESPONDENT_HOME_IAC_SERVICE_USER: ((ci_security_user_name))
      RESPONDENT_HOME_IAC_SERVICE_PASSWORD: ((ci_security_user_password))
      SAMPLE_USERNAME: ((ci_security_user_name))
      SAMPLE_PASSWORD: ((ci_security_user_password))
      SECURITY_USER_NAME: ((ci_security_user_name))
      SECURITY_USER_PASSWORD: ((ci_security_user_password))
      SURVEY_USERNAME: ((ci_security_user_name))
      SURVEY_PASSWORD: ((ci_security_user_password))

    all_services: &ci_all_services
    - ras-party-ci-deploy
    - ras-backstage-ci-deploy
    - ras-frontstage-ci-deploy
    - django-oauth2-test-ci-deploy
    - response-operations-ui-ci-deploy
    # TODO: Add 1 line
    - respondent-home-ui-ci-deploy
    - ras-secure-message-ci-deploy
    - ras-collection-instrument-ci-deploy
    - rm-action-service-ci-deploy
    - rm-actionexporter-service-ci-deploy
    - rm-case-service-ci-deploy
    - rm-collection-exercise-ci-deploy
    - iac-service-ci-deploy
    - rm-notify-gateway-ci-deploy
    - rm-sample-service-ci-deploy
    - rm-sdx-gateway-ci-deploy
    - rm-survey-service-ci-deploy
    - sdc-uaa-ci-deploy

    # TODO: add below block
    service_endpoints_for_ruby: &ci_service_endpoints_for_ruby
      RESPONDENT_HOME_EQ_HOST: eq-server
      RESPONDENT_HOME_EQ_PORT: '5000'
      RESPONDENT_HOME_EQ_PROTOCOL: http
      RESPONDENT_HOME_IAC_SERVICE_HOST: iac-service-ci.apps.devtest.onsclofo.uk
      RESPONDENT_HOME_IAC_SERVICE_PORT: '80'
      RESPONDENT_HOME_IAC_SERVICE_PROTOCOL: 'http'

resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
# TODO: Add below block, use master when merged
- name: respondent-home-ui-source
  type: git
  source:
    uri: https://github.com/ONSdigital/respondent-home-ui.git
#    branch: master
    branch: ssd

- name: cf-resource-ci
  type: cf
  source:
    api: ((cloudfoundry_api))
    username: ((cloudfoundry_email))
    password: ((cloudfoundry_password))
    organization: rmras
    space: ci
    skip_cert_check: true

jobs:
# TODO: Add block, including timer
- name: respondent-home-ui-ci-deploy
  serial_groups: [respondent-home-ui-ci-deploy]
  plan:
  - get: respondent-home-ui-source
    trigger: true
#  - get: ci-teardown-timer
#    trigger: true
#    passed: [ci-teardown]
  - task: bundle-respondent-home-ui
  # TODO: Need to push this task to the branch for it to work, so doing it inline for now
#    file: ras-deploy/tasks/respondent-home-ui/bundle-respondent-home-ui.yml
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
          tag: "latest"
      inputs:
        - name: respondent-home-ui-source
      outputs:
        - name: respondent-home-ui-source-bundle
          path: respondent-home-ui-source-bundle
      run:
        path: sh
        args:
        - -exc
        - |
          cd respondent-home-ui-source
          bundle package --all
          cd ..
          cp -r respondent-home-ui-source/* respondent-home-ui-source-bundle
  - put: push-app
    resource: cf-resource-ci
    params:
      current_app_name: respondent-home-ui-ci
      manifest: respondent-home-ui-source-bundle/manifest.yml
      path: respondent-home-ui-source-bundle
      environment_variables:
        <<: *ci_security_user
        <<: *ci_service_endpoints_for_ruby
        RESPONDENT_HOME_ANALYTICS_ACCOUNT: ((ci_respondent_home_analytics_account))
        RESPONDENT_HOME_LOCALE: 'en'
        RESPONDENT_HOME_EQ_PUBLIC_KEY: ((ci_respondent_home_eq_public_key))
        RESPONDENT_HOME_EQ_PRIVATE_KEY: ((ci_respondent_home_eq_private_key))