---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
- name: ras-deploy

run:
  path: ras-deploy/scripts/cloudfoundry-scripts/clear_space.sh